
title = 'model-config-file'

learning_rate = 0.001
epochs = 10
alpha_val = 0.01

[default]

output_size = 4

[lstm_glove]

embedding = 50
hidden_nodes = 256
bidirectional = false

[lstm_bert]

embedding = 768
hidden_nodes = 256