
title = 'model-config-file'

learning_rate = 0.001
epochs = 10
alpha_val = 0.01

[default]

output_size = 4

[lstm_glove]

embedding = 50
layers = 1
hidden_nodes = 256

[lstm_bert]

embedding = 768
layers = 1
hidden_nodes = 256